# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# Install
# 1. pip install pre-commit
# 2. pre-commit install(the first time you download the repo, it will be cached for future use)
repos:
  - repo: local
    hooks:
      - id: check-license
        name: Check copyright headers
        entry: python tools/check_license.py
        args: [--fix]
        language: system
        files: \.(py|cpp|cc|cxx|c|h|hpp|cu|cuh|hip)$
        exclude: ^3rdparty/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-ast
      - id: check-case-conflict
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.12
    hooks:
      - id: ruff-check
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.6
    hooks:
      - id: clang-format
        args: [--style=file]
        files: \.(cpp|c|cc|cu|h|hpp|cuh)$
